### ISSUE TITLE
Colourising glitch with c() in function args

### ISSUE THREAD

**Issue by Hong-Revo** [textmate/r.tmbundle#13]
(Originally posted at [MikhailArkhipov/vscode-r/#25](https://github.com/MikhailArkhipov/vscode-r/issues/25))

Specifically, when you have `c("a", "b", ...)` as a default function argument, the strings except for the first one are not coloured as text:

![image](https://user-images.githubusercontent.com/11328890/52995267-36af0f00-346e-11e9-8605-5a37a53d2c48.png)

It only appears to happen when the `c` function is used; you can see that `list` doesn't have this problem.

**Comment by Hong-Revo** [comment]
This is using Visual Studio Code, but I'm told that it uses TextMate grammars.

**Comment by Bibiko** [comment]
Hi. Using TextMate version 2.0-rc.22 no problem



Cheers, Hans

**Comment by tbates** [comment]
No problem here either (2.0-rc.27) - can be closed, IMHO.

```R
function(a=c("a", "b", "c")){}
```

**Comment by Hong-Revo** [comment]
Thanks, this appears to be specific to VSCode. Reposted there.
