### ISSUE TITLE
Matching paris are not closed automatically

### ISSUE THREAD

**Issue by FreshRamen** [textmate/r.tmbundle#9]
I've noticed that when using the R bundle, matching pairs of (, {, [, etc, are not closed automatically, even though the `disableTypingPairs` is set to FALSE on my machine. 

Is it locally deactivated by the bundle, or is this unexpected behavior that is just happening on my setup?

**Comment by FreshRamen** [comment]
As far as I can tell, there is no settings item for matching pairs. I created one quickly, which fixes it at least temporarily.

**Comment by infininight** [comment]
R documents should pickup the default setting from the Source bundle so a R specific settings wasn't needed. Make sure you have not disabled the following bundles:

Source, Text, TextMate, SCM, Bundle Support

They provide some basic defaults and should not be disabled.

**Comment by FreshRamen** [comment]
I actually have all these bundles enabled, but parenthesis completion still didn't work unless a setting was supplied. Markdown, ruby, and other bundles I use to in fact provide an explicit setting for parenthesis matching. Am I missing something?

**Comment by infininight** [comment]
You can see where settings are loading from with:

Open an R document, ⌃⌘T (Control-command-T), click settings, type `smarttypingpairs`

This will show you the active `smarttypingpairs` setting items with overridden ones crossed out. You should see one from Text overridden and one Source one active.

**Comment by FreshRamen** [comment]
Thanks for the steps. It's strange, there is nothing there. I guess this is a local issue.

**Comment by FreshRamen** [comment]
Ok I found the problem. I had installed the bundles but they weren't activated. I wasn't aware until now that those were two different things. Sorry for the misunderstanding. And thanks for your help of course!
